<?php

namespace App\Filament\Resources\FaresResource\Pages;

use App\Models\User;
use Filament\Actions;
use Illuminate\Support\Facades\Auth;
use App\Filament\Resources\FaresResource;
use Filament\Notifications\Actions\Action;
use Filament\Resources\Pages\CreateRecord;
use Filament\Notifications\Notification;

class CreateFares extends CreateRecord
{
    protected static string $resource = FaresResource::class;

    protected function getRedirectUrl(): string
    {
        return $this->getResource()::getUrl('index');
    }

    protected function getCreatedNotification(): ?Notification
    {
        $fare = $this->record;

        $auth = Auth::user();
        // Get a list of users with roles "admin" and "moderator"
        $usersWithRoles = User::whereHas('roles', function ($query) {
            $query->whereIn('id', [1, 2]);
        })->get();

        // Send the notification to each user
        foreach ($usersWithRoles as $user) {
            $notification = Notification::make()
                ->success()
                ->icon('heroicon-o-presentation-chart-bar')
                ->title('Fare Resource Created')
                ->body("New Fare {$fare->code} Generated by {$auth->name}!")
                ->actions([Action::make('View')->url(FaresResource::getUrl('edit', ['record' => $fare]))])
                ->sendToDatabase($user);
        }

        return $notification; // or return a notification if needed
    }
}
