<?php

namespace App\Filament\Resources\CardResource\Pages;

use App\Models\User;
use Illuminate\Support\Facades\Auth;
use App\Filament\Resources\CardResource;
use Filament\Notifications\Notification;
use Filament\Notifications\Actions\Action;
use Filament\Resources\Pages\CreateRecord;

class CreateCard extends CreateRecord
{
    protected static string $resource = CardResource::class;

    protected function getCreatedNotificationTitle(): ?string
    {
        return 'New Card Generated';
    }

    protected function getRedirectUrl(): string
    {
        return $this->getResource()::getUrl('index');
    }

    protected function getCreatedNotification(): ?Notification
    {
        $card = $this->record;

        $auth = Auth::user();
        // Get a list of users with roles "admin" and "moderator"
        $usersWithRoles = User::whereHas('roles', function ($query) {
            $query->whereIn('id', [1, 2]);
        })->get();

        // Send the notification to each user
        foreach ($usersWithRoles as $user) {
            $notification = Notification::make()
                ->success()
                ->icon('heroicon-o-credit-card')
                ->title('Card Resource Created')
                ->body("New Card {$card->card_id} Generated by {$auth->name}!")
                ->actions([Action::make('View')->url(CardResource::getUrl('edit', ['record' => $card]))])
                ->sendToDatabase($user);
        }

        return $notification; // or return a notification if needed
    }
}
