<?php

namespace App\Filament\Resources\TripResource\Pages;

use Filament\Actions;
use App\Models\User;
use App\Filament\Resources\TripResource;
use Illuminate\Support\Facades\Auth;
use Filament\Notifications\Notification;
use Filament\Resources\Pages\CreateRecord;
use Filament\Notifications\Actions\Action;

class CreateTrip extends CreateRecord
{
    protected static string $resource = TripResource::class;
    
    protected function getRedirectUrl(): string
    {
        return $this->getResource()::getUrl('index');
    }

    protected function getCreatedNotification(): ?Notification
    {
        $trip = $this->record;

        $auth = Auth::user();
        // Get a list of users with roles "admin" and "moderator"
        $usersWithRoles = User::whereHas('roles', function ($query) {
            $query->whereIn('id', [1, 2]);
        })->get();

        // Send the notification to each user
        foreach ($usersWithRoles as $user) {
            $notification = Notification::make()
                ->success()
                ->icon('heroicon-o-map-pin')
                ->title('Trip Resource Created')
                ->body("New Trip {$trip->name} Generated by {$auth->name}!")
                ->actions([Action::make('View')->url(TripResource::getUrl('edit', ['record' => $trip]))])
                ->sendToDatabase($user);
        }

        return $notification; // or return a notification if needed
    }
}
