<?php

namespace App\Filament\Resources\PermissionResource\Pages;

use App\Models\User;
use Filament\Actions;
use Illuminate\Support\Facades\Auth;
use Filament\Notifications\Notification;
use Filament\Notifications\Actions\Action;
use Filament\Resources\Pages\CreateRecord;
use App\Filament\Resources\PermissionResource;

class CreatePermission extends CreateRecord
{
    protected static string $resource = PermissionResource::class;
    
    protected function getCreatedNotificationTitle(): ?string
    {
        return 'New Permission Generated';
    }

    protected function getRedirectUrl(): string
    {
        return $this->getResource()::getUrl('index');
    }

    protected function getCreatedNotification(): ?Notification
    {
        $permission = $this->record;

        $auth = Auth::user();
        // Get a list of users with roles "admin" and "moderator"
        $usersWithRoles = User::whereHas('roles', function ($query) {
            $query->whereIn('id', [1, 2]);
        })->get();

        // Send the notification to each user
        foreach ($usersWithRoles as $user) {
            $notification = Notification::make()
                ->success()
                ->icon('heroicon-o-key')
                ->title('Permission Resource Created')
                ->body("New Permission {$permission->name} Generated by {$auth->name}!")
                ->actions([Action::make('View')->url(PermissionResource::getUrl('edit', ['record' => $permission]))])
                ->sendToDatabase($user);
        }

        return $notification; // or return a notification if needed
    }
}
